### ISSUE TITLE
Add support for Python 3.8.5

### ISSUE THREAD

**Issue by ZeroCool940711** [blipk/StreamlitExtras#1]
Hi there, first of all, thanks for this awesome component, I think it will be really helpful and solve a lot of issues we have on our [WebUI ](https://github.com/Sygil-Dev/sygil-webui)once we start using it in there, unfortunately we are for now stuck using python 3.8.5 on our environment and this component requires python 3.9 or higher. I would really appreciate if you could add support for python 3.8.5, I'm really interested in things like the threader, logger and router from this component, the other parts of this component also might fit in some way in our UI but for now those I mentioned are the ones I'm most interesting in as they will solve a lot of issues we have and allow us to do a lot more stuff with streamlit. Thanks for your time.

**Comment by blipk** [comment]
Sure, it was only dict unions requiring 3.9+
Have changed to a different dict merge and dropped the required version to 3.5+
If you have any other issues, please open another issue report.

Thanks.

**Comment by ZeroCool940711** [comment]
@blipk after the recent change you made I can now install it on python 3.8.5 but stil getting some errors on it:
```
    from streamlitextras.threader import lock, trigger_rerun, \
  File "d:\python\envs\ldm\lib\site-packages\streamlitextras\__init__.py", line 1, in <module>
    from .router import Router
  File "d:\python\envs\ldm\lib\site-packages\streamlitextras\router\__init__.py", line 6, in <module>
    from streamlitextras.logger import log
  File "d:\python\envs\ldm\lib\site-packages\streamlitextras\logger\__init__.py", line 8, in <module>
    from streamlitextras.utils import repr_
  File "d:\python\envs\ldm\lib\site-packages\streamlitextras\utils.py", line 7, in <module>
    def repr_(cls, ignore_keys: Optional[list[str]] = None, only_keys: Optional[list[str]] = None) -> str:
TypeError: 'type' object is not subscriptable
```

**Comment by blipk** [comment]
@ZeroCool940711 

Looks like prior to 3.9 the standard collections can't be used as type hints.
Need to change the typehints from list, tuple etc to typing.List, typing.Tuple

I don't really have the time to go through all the code and do that.
Feel free to submit a PR with typehints that will suit your python version.

Thanks.
