### ISSUE TITLE
Authentication logging out on Streamlit Cloud

### ISSUE THREAD

**Issue by RCambier** [blipk/StreamlitExtras#6]
Hey, fantastic work on the package!

Thanks to you I could set up an authentication, and it works perfect in local development.

However, once I deployed to the Streamlit Cloud, it loses the user authentication at every manual refresh of the page. 

I isolated the problem as the following: the `_get_websocket_headers()` that is used by the authentication system to retrieve the Cookies, does not return any cookies once deployed on the Streamlit Cloud. I'm not sure why, because I can see the Cookies in the Websocket headers by inspecting the page.

Here is what `_get_websocket_headers` returns in both situations:
Localhost:
```
{
  "Host": "localhost:8501",
  "Connection": "Upgrade",
  "Pragma": "no-cache",
  "Cache-Control": "no-cache",
  "User-Agent": "[redacted]",
  "Upgrade": "websocket",
  "Origin": "[redacted]",
  "Sec-Websocket-Version": "13",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "[redacted]",
  "Cookie": "[redacted]",
  "Sec-Websocket-Key": "[redacted]",
  "Sec-Websocket-Extensions": "permessage-deflate; client_max_window_bits",
  "Sec-Websocket-Protocol": "streamlit"
}
```

Streamlit Cloud
```
{
  "Host": "[redacted]",
  "User-Agent": "[redacted]",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "[redacted]",
  "Cache-Control": "no-cache",
  "Connection": "Upgrade",
  "Origin": "[redacted]",
  "Pragma": "no-cache",
  "Sec-Websocket-Extensions": "permessage-deflate; client_max_window_bits",
  "Sec-Websocket-Key": "[redacted]",
  "Sec-Websocket-Protocol": "streamlit",
  "Sec-Websocket-Version": "13",
  "Upgrade": "websocket",
  "X-Forwarded-For": "[redacted]",
  "X-Streamlit-User": "[redacted]"
}
```

In the meantime, I seem to be able to fix it by fetching the cookie from the cookie_manager instead of the websocket headers. So I do it the following way: 

```python
class CustomAuthenticator(Authenticator):
    @property
    def auth_cookie(self):
        """
        Gets the auth cookie from javascript cookies instead of
        Websocket headers. As the websocket method does not
        work on Streamlit Cloud

        :returns: Returns the auth cookie or None if it doesnt exist
        """
        logger.info("Running custom auth cookie fetching")
        if "authentication_token" in st.session_state and st.session_state["authentication_token"]:
            auth_cookie = st.session_state["authentication_token"]
            return auth_cookie

        cookie = None
        cookie_manager = get_cookie_manager()
        cookie = cookie_manager.get(AUTH_COOKIE_NAME)
        logger.info(f"Done running. Found: {cookie}")
        return cookie


def check_auth(title):
    global auth
    auth = get_auth(AUTH_COOKIE_NAME)
    auth = CustomAuthenticator(
        cookie_name=auth.cookie_name,
        cookie_key=auth.cookie_key,
        session_expiry_seconds=auth.session_expiry_seconds,
        session_name=auth.session_name,
        authenticator_name=auth.authenticator_name,
        user_class=auth.user_class,
        admin_ids=auth.admin_ids,
        developer_ids=auth.developer_ids,
        require_email_verification=auth.require_email_verification,
        debug=auth.debug,
    )
    logger.info(f"auth: {auth}")
    auth.delayed_init()  # This is required to make sure current Authenticator stays in session state
    auth_status = auth.auth_status
    logger.info(f"auth_status: {auth_status}")
    user = auth.current_user
    logger.info(f"user: {user}")
    if not auth_status or not user:
        auth_page(title)
        st.stop()
```

It works pretty OK, except that it usually refreshes the page once at least on every authentication check. 

Not sure how to handle this in the best way. Maybe you have an idea?
Thanks a lot!

**Comment by blipk** [comment]
Hey @RCambier 

I was previously using the Cookie Manager to get the cookies but that had problems of its own (component initialization would enter race conditions with the rest of streamlit and sometimes not set or get cookies) - maybe I can look at reimplementing as a fallback for the websocket headers.

Not sure when I will get to that but looks like your solution is working for you.

Would welcome a PR or any comments you might realize while using it this way.

**Comment by blipk** [comment]
I've updated the repo code to check the cookie manager componenet if it doesn't find it's cookie name in the websocket headers, you also have to set `attempt_fallback_cookies=True` when initializing Authenticator.

You can see the commit changes here: https://github.com/blipk/StreamlitExtras/commit/ed964466f201adee03b64c78cee35a691ac80b5d

You can simplify your code to below:

```Python
from streamlitextras.authenticator import get_auth

def check_auth(title):
    global auth
    auth = get_auth(AUTH_COOKIE_NAME, attempt_fallback_cookies=True)
    logger.info(f"auth: {auth}")
    auth.delayed_init()  # This is required to make sure current Authenticator stays in session state
    auth_status = auth.auth_status
    logger.info(f"auth_status: {auth_status}")
    user = auth.current_user
    logger.info(f"user: {user}")
    if not auth_status or not user:
        auth_page(title)
        st.stop()
```

Let me know how that works for you.
