### ISSUE TITLE
Direct Google OAuth2 without Firebase

### ISSUE THREAD

**Issue by ZupoLlask** [blipk/StreamlitExtras#7]
Dear @blipk,

I'm considering to use this component, as your code really seems robust (I'm still playing with Mohammed's CookieManager to learn a bit more about Streamlit execution model gripes).

Are you considering to directly support Google OAuth2 without the need of using Firebase service?

Thank you!

**Comment by blipk** [comment]
No

**Comment by ZupoLlask** [comment]
Are you open to accept a PR adding support for this or you think it's out of the scope of your component?

Thanks!

**Comment by blipk** [comment]
I'm not sure how well it would work, but you're welcome to submit a PR that I can review.
