### ISSUE TITLE
union types error

### ISSUE THREAD

**Issue by DerinChiu** [blipk/StreamlitExtras#8]
Hi, @blipk 
Thanks for your work, this repo does help a lot.
Encounters an error after upgrading to 0.2.41, using Python3.9.2.

  File "/.venv/lib/python3.9/site-packages/streamlitextras/cookiemanager/__init__.py", line 5, in <module>
    from streamlitextras.logger import log
  File "/.venv/lib/python3.9/site-packages/streamlitextras/logger/__init__.py", line 137, in <module>
    def bind_log(extras: dict | None = None) -> Logger:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Union types is a new feature in Python3.10+, so Python3.10+ is required in future versions?

**Comment by blipk** [comment]
Yes, I have migrated much of the typing to the 3.10+ format already, some other things may not work.

I will roll back this change, but some other parts of the modules are already using this notation.

I suggest using an older version of this module, or upgrading your python version as future updates will only be 3.10+.
